# Generated by Django 4.2.1 on 2023-05-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Название')),
                ('Sort', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('Description_before', models.TextField(verbose_name='Описание - ДО прохождения')),
                ('Description_after', models.TextField(verbose_name='Описание - ПОСЛЕ прохождения')),
                ('Comment', models.TextField(verbose_name='Комментарий для преподавателя')),
                ('Write_time', models.BooleanField(verbose_name='Записывать время прохождения?')),
                ('Limit_time', models.IntegerField(verbose_name='Необходимое время на выполнение (минуты)')),
                ('Mix_Question', models.BooleanField(verbose_name='Перемешивать вопросы?')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
    ]
